- name: restart collectd
  service: name=collectd state=restarted
  become: yes
  tags:
    - monitoring

- name: restart rsyslog
  service: name=rsyslog state=restarted
  become: yes
  tags:
   - rsyslog
   - mozstash
