---
# if one wants to replicate in more than one influxDB all you need to do is to add a entry here in the list influxdb_host

collectd_install_recommends: True
collectd_interval_seconds: 20
collectd_load_plugins:
      - bind
      - cpu
      - df
      - load
      - memory
      - network
      - processes
      - swap
      - uptime
      - vmem
collectd_log_dir:  "{{ base_data_dir }}/collectd"
collectd_python_plugin_dir:  "/usr/share/collectd/python"
