- name: Create directories which need to exist if necessary
  file: path={{ item }} state=directory owner=root
  with_items:
    - "{{ monitoring_tmp_dir }}"
  sudo: yes
  tags:
    - monitoring
    - statsd
    - statsd-fe-influxdb

- name: Download telegraf package
  get_url: url="{{ telegraf_download_url_path_prefix }}/telegraf_{{ telegraf_version }}_amd64.deb" dest="{{ monitoring_tmp_dir }}"
  sudo: yes
  tags:
    - monitoring
    - statsd
    - statsd-fe-influxdb

- name: Install telegraf
  apt: deb="{{ monitoring_tmp_dir }}/telegraf_{{ telegraf_version }}_amd64.deb"
  sudo: yes
  notify: restart telegraf
  tags:
    - monitoring
    - statsd
    - statsd-fe-influxdb

- name: Configure telegraf
  template: src="telegraf.conf.j2" dest="/etc/telegraf/telegraf.conf"
  sudo: yes
  notify: restart telegraf
  tags:
   - monitoring
   - statsd
   - statsd-fe-influxdb

#TODO: Add/enable a probe so as to monitor this particular statsd instance and alert on failure
