---

monitoring_tmp_dir: "{{ base_monitoring_dir }}/tmp"
influx_data_dir: "{{ base_monitoring_dir }}/influxdb"

influxdb_version: "0.12.2-1"

# Needed for first install. Subsequently setting this to true will drop existing downsampled data (if any.)
reapply_retentions_and_cqs: false
# Create users, dbs and grant permissions after wall flushing is done
create_db_users_grant_permissions: false

influx_backup_snitch_keys:
     dalstgmesos01: "{{ influx91_backup_snitch_key }}"
     dalstgmesos02: "{{ influx92_backup_snitch_key }}"
     dalstgmesos03: "{{ influx93_backup_snitch_key }}"
     dalstgmesos04: "{{ influx94_backup_snitch_key }}"
     dalinfluxdb1: "{{ influx1_backup_snitch_key }}"

collectd_types_dbs_contents:
    - "{{ lookup('file', 'types.db') }}"
    - "{{ lookup('file', '../../monitoring-agent/files/collectd-plugins/docker/dockerplugin.db') }}"
