---
- name: verify docker
  command: which docker
  register: which_docker_result
  ignore_errors: True

- include: docker.yml
  static: no
  when: which_docker_result.rc == 0

- include: pkgs.yml
  static: no
  when: which_docker_result.rc != 0
