---
- name: install packages
  package:
    name: "{{ items }}"
  with_items:
    - nodejs
    - git

- name: clone statsd
  git:
    repo: https://github.com/etsy/statsd.git
    dest: /opt/statsd
    version: v0.7.2

- name: local npm installs
  npm:
    name: statsd-influxdb-backend
    path: /opt/statsd

- name: global npm installs
  npm:
    name: pm2
    version: '0.12.10'
    global: yes
