- name: Create directories which need to exist if necessary
  file: path={{ item }} state=directory owner=root
  with_items:
    - "{{ monitoring_tmp_dir }}"
  become: yes
  tags:
    - monitoring

- name: Download influxdb package
  get_url: url="{{ influxdb_download_url_path_prefix }}influxdb_{{ influxdb_version }}_amd64.deb" dest="{{ monitoring_tmp_dir }}"
  become: yes
  tags:
    - monitoring

- name: Install influxdb
  apt: deb="{{ monitoring_tmp_dir }}/influxdb_{{ influxdb_version }}_amd64.deb"
  become: yes
  notify: restart influxdb
  tags:
    - monitoring

- name: Configure influxdb
  template: src="influxdb.conf.j2" dest="/etc/influxdb/influxdb.conf"
  become: yes
  notify: restart influxdb
  tags:
   - monitoring

# Disabled.  Apparently this configuration file does not cause influx to write
# to the specified log files.  Bug in 0.9.2?  Leaving it in for further
# experimentation.
# - name: Configure influxdb defaults
#  template: src="influxdb.default.j2" dest="/etc/default/influxdb"
#  become: yes
#  notify: restart influxdb
#  tags:
#    - monitoring

- name: Remove init.d script for influxdb
  file: path=/etc/init.d/influxdb state=absent
  become: yes
  tags:
    - monitoring

- name: Install upstart script for influxdb
  template: src=influxdb.conf.init.j2 dest=/etc/init/influxdb.conf
  become: yes
  notify: restart influxdb
  tags:
    - monitoring

- name: Create influx data directories that need to exist, if necessary
  file: path={{ item }} state=directory group=influxdb owner=influxdb
  with_items:
    - "{{ influx_data_dir }}"
    - "{{ influx_data_dir }}/data"
    - "{{ influx_data_dir }}/hh"
    - "{{ influx_data_dir }}/log"
    - "{{ influx_data_dir }}/meta"
    - "{{ influx_data_dir }}/plugin"
    - "{{ influx_data_dir }}/plugin/collectd"
    - "{{ influx_data_dir }}/backup"
    - "{{ influx_data_dir }}/backup_logs"
    - "{{ influx_data_dir }}/scripts"
    - "{{ influx_data_dir }}/wal"
  become: yes
  notify: restart influxdb
  tags:
    - monitoring
    - influx_backup

# Creating a concatenated types.db (as the influxdb collectd plugin currently does not support multiple typesdb file)
- name: Create merged types.db for collectd plugin
  template: src=merged_types.db.j2 dest="{{ influx_data_dir }}/plugin/collectd/types.db"
  become: yes
  notify: restart influxdb
  tags:
    - monitoring

# Disabled.  I've been unable to have influx log to the files I want.
#
# - name: Put influxdb logs under logrotate control
#  template: src=influxdb.logrotate.j2 dest=/etc/logrotate.d/influxdb
#  become: yes
#  tags:
#    - monitoring

# Temporary log rotator until the influxdb default file is respected by influx on start
- name: Rotate influxdb log (temp)
  template: src=influxdb.logrotate.tmp.j2 dest=/etc/logrotate.d/influxdb
  become: yes
  tags:
    - monitoring

# Copy Retention policies and Continuous queries script to influx host
- name: Copying retention policies and continuous queries on influx host
  template: src=influxdb.retention.j2 dest=/tmp/influxdb.retention.sh
  when: reapply_retentions_and_cqs
  tags:
    - retention_policy

# Applying retention policies and continuous queries on influx database
- name: Applying retention policies and continuous queries on influx database
  command: "{{ item }}"
  with_items:
    - sh /tmp/influxdb.retention.sh
    - rm /tmp/influxdb.retention.sh
  when: reapply_retentions_and_cqs
  tags:
    - retention_policy

# Copy Influx users script to influx hosts
- name: Influx users script to influx hosts
  template: src=influxdb.users.sh.j2  dest=/tmp/influxdb.users.sh
  when: create_db_users_grant_permissions
  tags:
    - influx_users

# Creating admin and non admin users with privileges on influx hosts
- name: Creating admin and non admin users with privileges on influx hosts
  command: "{{ item }}"
  with_items:
    - sh /tmp/influxdb.users.sh
    - rm /tmp/influxdb.users.sh
  when: create_db_users_grant_permissions
  tags:
    - influx_users

# Copy Influx backup script to influx hosts
- name: Influx backup script to influx hosts
  template: src=influxdb.backup.sh.j2  dest={{ influx_data_dir }}/scripts/influxdb.backup.sh mode=0775
  become: yes
  tags:
    - influx_backup

# Running daily backup script as a cronjob on influx hosts
- name: Running backup script as a cronjob on influx hosts
  cron: name="Backup script" minute="59" hour="14,23" user="root" job="bash -c '{{ influx_data_dir }}/scripts/influxdb.backup.sh >> {{ influx_data_dir }}/backup_logs/influx_backup_$(date +\"\\%Y\\%m\").log'"
  become: yes
  tags:
    - influx_backup

# Since the complete backup job takes longer, we schedule to run earlier than 23:59 hrs on Thursday,
# else snitch triggers an alert. The remove timestamp file cron job that runs before this job will trigger a complete backup.
- name: Running complete backup script as a cronjob on influx hosts
  cron: name="Complete Backup job" minute="59" hour="20" weekday="4" user="root" job="bash -c '{{ influx_data_dir }}/scripts/influxdb.backup.sh >> {{ influx_data_dir }}/backup_logs/influx_backup_$(date +\"\\%Y\\%m\").log'"
  become: yes
  tags:
    - influx_backup

# Remove backup timestamp file on Thursday of every week. This will trigger a complete backup on Thursday every week at 11:59am
- name: Remove backup timestamp file on Thursday of every week
  cron: name="Remove backup timestamp" minute="59" hour="11" weekday="4" user="root" job="rm {{ influx_data_dir }}/backup/last_backup_timestamp"
  become: yes
  tags:
    - influx_backup

# Copy Influx databases creation script to influx hosts
- name: Influx databases copy script
  template: src=influxdb.create_dbs.sh.j2  dest=/tmp/influxdb.create_dbs.sh
  tags:
    - create_influx_databases

# Creating databases on influx hosts
- name: Creating influx databases
  command: "{{ item }}"
  with_items:
    - bash /tmp/influxdb.create_dbs.sh
    #- rm /tmp/influxdb.create_dbs.sh
  tags:
    - create_influx_databases
