---
# Main task for setting up monitoring agents (collectd and similar/related) on the machines.

- hosts: monitored

  # To avoid these prompts supply the values from the command line using ansible playbook extra vars "-e". Example:
  #     $ anisble-playbook -i /path/to/inventory -e "marathon_collectd_user=username" -e "marathon_collectd_pass=password" monitoring-agent.yml
  vars_prompt:
    - name: "marathon_collectd_user"
      prompt: "Marathon user for collectd (used only if marathon auth is enabled; read-only access required)?"
      default: "collectd"
      private: no

    - name: "marathon_collectd_pass"
      prompt: "Marathon password for collectd (used only if marathon auth is enabled)?"
      default: ""
      private: yes

  roles:
    - monitoring-agent
